# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: It's psk blog
description: > 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://psk11.github.io" # the base hostname & protocol for your site
github_username:  psk11

# Build settings
markdown: kramdown
